title: Clean Architecture Docker .NET Angular
description: Documentation for the Clean Architecture project
remote_theme: just-the-docs/just-the-docs

url: https://nitin27may.github.io/clean-architecture-docker-dotnet-angular

# Version information
version: "2.1.0"
last_updated: "2023-06-15"
build_timestamp: <%= Time.now.to_i %>

# Cache busting settings
cache_bust: true
asset_version_query: <%= Time.now.to_i %>

# Enable search
search_enabled: true

# Enable support for hyphenated search keywords
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/nitin27may/clean-architecture-docker-dotnet-angular"

# Footer content
footer_content: "Copyright &copy; 2025 Nitin Kumar. Distributed under the MIT License."

# Footer version display
footer_version_display: true
footer_version_text: "Version"

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Add spacing to fix title cropping issue
heading_anchors: true

# Fixed spacing configuration
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    color: blue
  new:
    color: green
  note:
    color: purple
  warning:
    color: red

# Set the proper spacing
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
  
# Add custom CSS for spacing
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/nitin27may/clean-architecture-docker-dotnet-angular"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Enable navigation structure
nav_external_links:
  - title: Clean Architecture on GitHub
    url: https://github.com/nitin27may/clean-architecture-docker-dotnet-angular
    hide_icon: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable collapsible navigation
collapse_inactive_chapters: true

# Enable copy code button
enable_copy_code_button: true

# Google Analytics tracking
ga_tracking: G-BJBJ6TYVWF
ga_tracking_anonymize_ip: true

# Force browser to reload CSS and JS
assets:
  source_maps: true
  destination: "/assets"
  compression: true
  gzip: false
  defaults:
    integrity:
      {css,js}: true
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  # Apply cache busting to assets
  cache_bust_strategy: hard
